name: Deploy to deta

on:
  push:
    branches:
      - master

jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Deta
        uses: neobrains/space-deployment-github-action@v0.5
        with:
          access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
          project_id: ${{ secrets.SPACE_ID }}
          project_directory: typeracer
          space_push: true
          list_on_discovery: false
