name: deploy to deta 

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: deploy to deta 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      uses: lizheming/deta-action@master
      with:
        access_token: ${{ secrets.space_access_token }}
        id: ${{ secrets.space_id }}
        version: "1.0.0"
        listed: false
        dir: "./typeracer"
